In [1]:
import numpy as np

In [2]:
a =  np.array([1,2,3,4,5,6])

In [4]:
b = np.zeros(3)
print(b)

[0. 0. 0.]


In [5]:
c = np.ones(4)
print(c)

[1. 1. 1. 1.]


In [6]:
d = np.empty(5)
print(d)

[0.00000000e+000 8.16592743e-312 8.16592741e-312 8.16592742e-312
 0.00000000e+000]


In [8]:
e = np.arange(6)
print(e)

[0 1 2 3 4 5]


In [11]:
f = np.arange(2,20)
print(d)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [12]:
g= np.arange(2,20,2)
print(f)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [15]:
# Linerly space array
h = np.linspace(0,10,num=5)
print(h)

[ 0.   2.5  5.   7.5 10. ]


In [16]:
i = np.ones(5, dtype=np.int8)
print(i)

[1 1 1 1 1]


In [17]:
j = np.ones(5, dtype=np.float64)
j

array([1., 1., 1., 1., 1.])