In [5]:
import numpy as np

In [2]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
b = np.ones((3,4))
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
c = np.empty((3,4))
c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
d = np.arange(24).reshape(2,3,4)
d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [9]:
sort = np.array([2,3,4,5,65,9])
sort.sort()

In [10]:
sort

array([ 2,  3,  4,  5,  9, 65])

In [14]:
e = np.array([2,3,4,5,20,38,478])

In [16]:
c = np.concatenate((sort,e))
print(c)

[  2   3   4   5   9  65   2   3   4   5  20  38 478]


## 2-D arrays

In [25]:
a1 = np.array([[1,2,3,4,5,6,7],[4,5,6,7,8,9,0]])
a1

array([[1, 2, 3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8, 9, 0]])

In [26]:
b1 = np.array([[6,7],[8,7]])
b1

array([[6, 7],
       [8, 7]])

In [ ]:
c1 = np.concatenate((a1,b1),axis=1) #axis 0 you write when dimension same
c1

array([[1, 2, 3, 4, 5, 6, 7, 6, 7],
       [4, 5, 6, 7, 8, 9, 0, 8, 7]])

In [31]:
c1.ndim

2

In [ ]:
# number of elements
c1.size

18

In [33]:
c1.shape

(2, 9)

In [39]:
a= np.arange(6)
print(a)
a = a.reshape(3,2) # 2*3=6 elements
print(a)

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


In [10]:
x=np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
y=x.reshape(3,3)
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.reshape(x,newshape=(1,9) ,order="C")

C:\Users\ssc\AppData\Local\Temp\ipykernel_4388\2792090052.py:1: DeprecationWarning: `newshape` keyword argument is deprecated, use `shape=...` or pass shape positionally instead. (deprecated in NumPy 2.1)
  np.reshape(x,newshape=(1,9) ,order="C")


array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])