In [2]:
import numpy as np

### Creating Array

In [3]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [5]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


### Higher Dimensional Arrays

In [6]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


### Indexing

In [7]:
arr = np.array([1, 2, 3, 4])
print(arr[1])

2


In [9]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [10]:
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [8]:
print(arr[2] + arr[3])

7


In [11]:
a = np.zeros(9)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [12]:
a = np.ones(6)
print(a)


[1. 1. 1. 1. 1. 1.]


In [15]:
a = np.arange(0, 15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [16]:
a = np.arange(0, 12,4)
print(a)

[0 4 8]


### Concatenate two arrray

In [18]:
a = np.array([1,2])
b = np.array([3,4])
print(np.concatenate([a,b]))

[1 2 3 4]


In [17]:
a = np.linspace(0, 2, 5)
print(a)

[0.  0.5 1.  1.5 2. ]


In [21]:
a = np.arange(18)
print(np.split(a, 3))

[array([0, 1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10, 11]), array([12, 13, 14, 15, 16, 17])]


### Sort Array

In [22]:
a = np.array([3,1,2,9,8,6,5,4])
print(np.sort(a))

[1 2 3 4 5 6 8 9]


### Sort Array index

In [24]:
a = np.array([3,17,8])
print(np.argsort(a))


[0 2 1]


### Basic function of array

In [25]:
print(np.max(a))

17


In [26]:
print(np.min(a))

3


In [27]:
print(np.sum(a))

28


In [28]:
print(np.mean(a))

9.333333333333334


### Remove duplicate values in the array

In [32]:
b = np.array([1,2,2,3,3,3])

print(np.unique(b))

[1 2 3]
