In [1]:
import numpy as np

### Reshape

In [7]:
# Reshape From 1-D to 2-D
arr = np.array([1, 2, 3, 4, 7, 6, 7, 8, 9, 0, 11, 12])
new_arr1 = arr.reshape(4, 3)
print(new_arr1)

[[ 1  2  3]
 [ 4  7  6]
 [ 7  8  9]
 [ 0 11 12]]


In [8]:
#Reshape From 1-D to 3-D
new_arr2 = arr.reshape(2, 3, 2)
print(new_arr2)

[[[ 1  2]
  [ 3  4]
  [ 7  6]]

 [[ 7  8]
  [ 9  0]
  [11 12]]]


In [10]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [12]:
new_arr3 = new_arr1.reshape(2,3,2)
print(new_arr3)

[[[ 1  2]
  [ 3  4]
  [ 7  6]]

 [[ 7  8]
  [ 9  0]
  [11 12]]]


### Flattening the arrays

In [13]:
arr_f = np.array([[1, 2, 3], [4, 5, 6]])
newarr_f = arr_f.reshape(-1)
print(newarr_f)

[1 2 3 4 5 6]


In [21]:
arr_f2 = np.array( [ [ [ 1 , 2],[ 3 , 4],[ 7 , 6] ],[[ 7 , 8],[ 9 , 0],[11 ,12]]])
newarr_f2 = arr_f2.reshape(-1)
print(newarr_f2)

[ 1  2  3  4  7  6  7  8  9  0 11 12]
